name: TourEase
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

# Environment configuration
environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies required for your Flutter project
dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  cupertino_icons: ^1.0.2           # Provides Cupertino style icons for iOS
  concentric_transition: ^1.0.3     # Custom page transition animations
  google_fonts: ^6.2.1              # Integration of Google Fonts
  font_awesome_flutter: ^10.7.0     # Font Awesome icons
  carousel_slider: ^4.2.1           # Carousel/slider widget

  # State Management and Navigation
  provider: ^6.1.5                  # State management solution
  get_it:                     # Service locator for dependency injection

  # Firebase Integration
  firebase_core: ^2.27.1            # Firebase initialization
  firebase_auth: ^4.17.9            # Firebase authentication
  cloud_firestore: ^4.15.9          # Firestore database integration

  # Local Storage
  shared_preferences: ^2.2.3        # Key-value storage for Flutter applications

  # Environment Variables
  flutter_dotenv: ^5.1.0            # Loading environment variables from .env file
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_storage: ^11.7.7
  avatar_glow: ^3.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.6
  googlemaps_flutter_webservices: ^1.0.2
  dio: ^5.8.0+1




# Development dependencies (e.g., testing frameworks)
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for Flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# Flutter-specific configuration for the project (optional)
flutter:
  # Indicates that the Material Icons font should be included
  uses-material-design: true

  # Specifies the assets used in the application
  assets:
    - assets/images/
    - assets/locations/
    - assets/avatars/
    # Add more asset directories as needed

  # Example of specifying fonts for the application (uncomment and modify as needed)
  # fonts:
  #   - family: ExampleFont
  #     fonts:
  #       - asset: fonts/example_font.ttf


flutter_launcher_icons:
  image_path: "assets/images/tourease_hd.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  image_path_android: "assets/images/tourease_hd.png"
  image_path_ios: "assets/images/tourease_hd.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/tourease_hd.png"
